### ISSUE TITLE
Hashroute support

### ISSUE THREAD

**Issue by telamon** [koffeine/svelte-router#1]
Hey!
Curious if hash-routing is part of the scope for this lib.
I might be using it wrong but otherwise really dig the minimalistic api :beers: 
```js
Router.init([
  { path: '/', component: () => Keygen },
  { path: '/#/pub', component: () => Pub },
  { path: '/#/shop', component: () => Shop },
  { path: '/#/msgs', component: () => Messages },
  { path: '/#/profile', component: () => Profile }
  // { path: '*', redirect: '/#/pub' } // <-- causes mayhem
])
```

**Comment by koffeine** [comment]
Hey @telamon!

No, it only supports the HTML5 History API.
There are no plans to support hash-based mode.

I'll add this info to the Readme.

**Comment by telamon** [comment]
Ok. Um aside from the infamous hash-based mode which i'm not sure i want...
Dosen't `/a#b` qualify as a unique path in the history API's?
Like i'm wondering why the above example failed in practice. :/

**Comment by koffeine** [comment]
The router uses location.pathname to determine the current url.

For example if you enter https://github.com/a#b and check out the location object in console,
you will see the following:

```js
{
    href: 'https://github.com/a#b',
    protocol: 'https:',
    host: 'github.com',
    hostname: 'github.com',
    port: '',
    pathname: '/a',
    hash: '#b',
    search: '',
}
```

As you can see the browser split the url into two parts by the `#` character,
because the hash part is used to link to a specific part on a page.
